version: "3.9"
services:
  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    volumes:
      - "./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/main.yml"
      - "./grafana/dashboards:/var/lib/grafana/dashboards"
      - "./grafana/datasources.yml:/etc/grafana/provisioning/datasources/main.yml"
      - "./grafana/grafana.ini:/etc/grafana/grafana.ini"
    networks:
      - pg_monitoring
    environment:
      NO_PROXY: localhost,127.0.0.1,prometheus,postgres-exporter
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - pg_monitoring
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    environment:
      NO_PROXY: localhost,127.0.0.1,prometheus,postgres-exporter
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:master
    ports:
      - "9187:9187"
    volumes:
      - "./postgres-exporter/queries.yaml:/etc/postgres_exporter/queries.yaml"
    networks:
      - pg_monitoring
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      NO_PROXY: localhost,127.0.0.1,prometheus,postgres-exporter
      DATA_SOURCE_NAME: postgresql://prometheus:prometheus@host.docker.internal:5432/portnov
      PG_EXPORTER_EXTEND_QUERY_PATH: /etc/postgres_exporter/queries.yaml

networks:
  pg_monitoring:
    driver: bridge
