# Sample config for Prometheus.

global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  #external_labels:
  #    monitor: 'example'

# Alertmanager configuration
#alerting:
#  alertmanagers:
#  - static_configs:
#    - targets: ['alertmanager:9093']

rule_files: []

scrape_configs:
  # Here it's Prometheus itself.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Postgres-exporter
  - job_name: postgres
    static_configs:
      - targets: ['postgres-exporter:9187']

