{
 "title": "Cluster Overview",
 "description": "postgres exporter Dashboard for display important postgreSQL metric",
 "tags": [ "postgresql" ],
 "time": { "from": "2024-04-24T18:22:00.901Z", "to": "2024-04-24T18:38:05.310Z" },
 "templating": {
  "list": [
   {
    "name": "Instance",
    "label": "Exporter",
    "query": {
     "query": "label_values({job=\"postgres\"},instance)"
    }
   },
   {
    "name": "Server",
    "query": {
     "query": "label_values({job=\"postgres\"},server)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "PostgreSQL Version",
   "type": "stat",
   "description": "Source: server_version_num",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_server_version_num{instance=\"$Instance\",server=\"$Server\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - pg_postmaster_start_time_seconds{instance=\"$Instance\",server=\"$Server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{instance=\"$Instance\",server=\"$Server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Time",
   "type": "stat",
   "description": "Total duration of all active database sessions within displayed time range. Note: if this number equals to displayed time period, this means one session has been active during the period (in average).",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(pg_stat_database_active_time_seconds_total{instance=\"$Instance\"}[$__range])) without (datname,datid)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Idle In Transaction Time",
   "type": "stat",
   "description": "Maximum duration of \"idle in transaction\" sessions",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_stat_activity_max_tx_duration{state=\"idle in transaction\",instance=\"$Instance\",server=\"$Server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checkpoints Count",
   "type": "stat",
   "description": "Total number of checkpoints within displayed time range",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(pg_stat_bgwriter_checkpoints_timed_total{instance=\"$Instance\"}[$__range])",
     "legendFormat": "By Time"
    },
    {
     "expr": "delta(pg_stat_bgwriter_checkpoints_req_total{instance=\"$Instance\"}[$__range])",
     "legendFormat": "By WAL"
    }
   ]
  },
  {
   "title": "Commit Ratio",
   "type": "gauge",
   "description": "Transaction committed vs rollbacked",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_xact_commit{instance=\"$Instance\"})/(sum(pg_stat_database_xact_commit{instance=\"$Instance\"}) + sum(pg_stat_database_xact_rollback{instance=\"$Instance\"}))"
    }
   ]
  },
  {
   "title": "Connections used",
   "type": "gauge",
   "description": "Percentage of max_connections used",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_numbackends)/max(pg_settings_max_connections)"
    }
   ]
  },
  {
   "title": "Shared Buffer Hits",
   "type": "gauge",
   "description": "Shared buffer hits vs reads from disc",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_blks_hit{instance=~\"$Instance\"})/(sum(pg_stat_database_blks_hit{instance=~\"$Instance\"})+sum(pg_stat_database_blks_read{instance=~\"$Instance\"}))*100"
    }
   ]
  },
  {
   "title": "Non-Frozen Transactions Age",
   "type": "gauge",
   "description": "Age of oldest non-frozen tuple across all databases. ",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(pg_database_freeze_age)", "legendFormat": "Age" },
    {
     "expr": "max(pg_settings_autovacuum_freeze_max_age)",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Database Bytes Hit + Read",
   "type": "stat",
   "description": "Total number of bytes read from data files and hit from buffer cache for displayed time range",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "8192 * sum(delta(pg_stat_database_blks_read[$__range]) + delta(pg_stat_database_blks_hit[$__range])) without (datname,datid)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Bytes Written",
   "type": "stat",
   "description": "Total number of bytes written to data files by checkpointer, bgwriter and backends, for displayed time range",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(delta(pg_stat_bgwriter_buffers_clean_total[$__range]) + delta(pg_stat_bgwriter_buffers_backend_total[$__range]) + delta(pg_stat_bgwriter_buffers_checkpoint_total[$__range]))*8192",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction rate",
   "type": "stat",
   "description": "Transactions committed + roolback per minute\n\nSource: pg_stat_database,xact_commit + xact_rollback",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((rate(pg_stat_database_xact_commit{instance=\"$Instance\"}[$__range])))+sum((rate(pg_stat_database_xact_rollback{instance=\"$Instance\"}[$__range])))"
    }
   ]
  },
  {
   "title": "WAL Bytes",
   "type": "stat",
   "description": "Total number of WAL bytes written for displayed time range",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(pg_stat_wal_wal_bytes{instance=\"$Instance\",server=\"$Server\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Sizes",
   "type": "bargauge",
   "description": "Current database sizes. Template databases are not shown.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{server = \"$Server\", instance=\"$Instance\", datname !~ \"template.*\" }",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Connections by State",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (state) (pg_stat_activity_count{instance=\"$Instance\",server=\"$Server\"})",
     "legendFormat": "__auto"
    },
    { "expr": "pg_settings_max_connections", "legendFormat": "threshold" }
   ]
  },
  {
   "title": "Database Size Growth",
   "type": "bargauge",
   "description": "Change of database sizes over displayed time period. Template databases are not shown.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(pg_database_size_bytes{server = \"$Server\", instance=\"$Instance\", datname !~ \"template.*\"}[$__range])",
     "legendFormat": "{{datname}}"
    }
   ]
  }
 ]
}