{
 "title": "Database Overview",
 "description": "postgres exporter Dashboard for display important postgreSQL metric",
 "tags": [ "postgresql" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Instance",
    "label": "Exporter",
    "query": {
     "query": "label_values({job=\"postgres\"},instance)"
    }
   },
   {
    "name": "Server",
    "query": {
     "query": "label_values({job=\"postgres\"},server)"
    }
   },
   { "name": "Database", "query": { "query": "label_values(datname)" } }
  ]
 },
 "panels": [
  {
   "title": "Database Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"$Database\",server=\"$Server\", instance=\"$Instance\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Database Size Growth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(pg_database_size_bytes{datname=\"$Database\",instance=\"$Instance\",server=\"$Server\"}[$__range])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Database Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(pg_stat_database_active_time_seconds_total{datname=\"$Database\",instance=\"$Instance\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Idle In Transaction Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_stat_activity_max_tx_duration{datname=\"$Database\",state=\"idle in transaction\",instance=\"$Instance\",server=\"$Server\"})",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Non-Frozen Transactions Age",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_freeze_age{datname=\"$Database\",server=\"$Server\",instance=\"$Instance\"}",
     "legendFormat": "Age"
    },
    {
     "expr": "pg_settings_autovacuum_freeze_max_age{instance=\"$Instance\",server=\"$Server\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Database Bytes Hit + Read",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(pg_stat_database_blks_read{datname=\"$Database\"}[$__range]) + delta(pg_stat_database_blks_hit{datname=\"$Database\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction rate",
   "type": "timeseries",
   "description": "Transactions committed + roolback per minute\n\nSource: pg_stat_database,xact_commit + xact_rollback",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum((rate(pg_stat_database_xact_commit{instance=\"$Instance\",datname=\"$Database\"}[$__range])))",
     "legendFormat": "Commits"
    },
    {
     "expr": "sum((rate(pg_stat_database_xact_rollback{instance=\"$Instance\",datname=\"$Database\"}[$__range])))",
     "legendFormat": "Rollbacks"
    }
   ]
  },
  {
   "title": "Connections by State",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum by (state) (pg_stat_activity_count{datname=\"$Database\",instance=\"$Instance\",server=\"$Server\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}