{
 "title": "Database Top Queries",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "Server",
    "query": {
     "query": "label_values({job=\"postgres\"},server)"
    }
   },
   {
    "name": "Instance",
    "label": "Exporter",
    "query": {
     "query": "label_values({job=\"postgres\"},instance)"
    }
   },
   { "name": "Database", "query": { "query": "label_values(datname)" } },
   {
    "name": "User",
    "query": {
     "query": "label_values({job=\"postgres\"},role)"
    }
   },
   { "name": "Top", "query": "10,20,30,50,100" }
  ]
 },
 "panels": [
  {
   "title": "Top by Planning Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk($Top, rate(pg_statement_top_total_plan_time_ms{datname=\"$Database\",instance=\"$Instance\",server=\"$Server\",role=\"$User\"}[$__rate_interval]))",
     "legendFormat": "{{queryid}}: {{query}}"
    }
   ]
  },
  {
   "title": "Top by Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk($Top, rate(pg_statement_top_total_exec_time_ms{datname=\"$Database\",instance=\"$Instance\",server=\"$Server\",role=\"$User\"}[$__rate_interval]))",
     "legendFormat": "{{queryid}}: {{query}}"
    }
   ]
  },
  {
   "title": "Top by Plans",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($Top, rate(pg_statement_top_exec_plans_total{datname=\"$Database\",instance=\"$Instance\",server=\"$Server\",role=\"$User\"}[$__rate_interval]))",
     "legendFormat": "{{queryid}}: {{query}}"
    }
   ]
  },
  {
   "title": "Top by Executions",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($Top, rate(pg_statement_top_exec_execs_total{datname=\"$Database\",instance=\"$Instance\",server=\"$Server\",role=\"$User\"}[$__rate_interval]))",
     "legendFormat": "{{queryid}}: {{query}}"
    }
   ]
  }
 ]
}