{
 "title": "Cluster IO",
 "description": "postgres exporter Dashboard for display important postgreSQL metric",
 "tags": [ "postgresql" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Instance",
    "label": "Exporter",
    "query": {
     "query": "label_values({job=\"postgres\"},instance)"
    }
   },
   {
    "name": "Server",
    "query": {
     "query": "label_values({job=\"postgres\"},server)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Data File Reads",
   "type": "timeseries",
   "description": "Shows volume read from data files (including OS page cache hits)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "8192*rate(pg_stat_database_blks_read{instance=\"$Instance\"}[$__rate_interval])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Data File Writes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(pg_stat_bgwriter_buffers_checkpoint_total{instance=\"$Instance\"}[$__rate_interval])*8192",
     "legendFormat": "Checkpoint"
    },
    {
     "expr": "rate(pg_stat_bgwriter_buffers_clean_total{instance=\"$Instance\"}[$__rate_interval])*8192",
     "legendFormat": "BgWriter"
    },
    {
     "expr": "rate(pg_stat_bgwriter_buffers_backend_total{instance=\"$Instance\"}[$__rate_interval])*8192",
     "legendFormat": "Backends"
    }
   ]
  },
  {
   "title": "Shared Buffer Allocations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "8192*rate(pg_stat_bgwriter_buffers_alloc_total{instance=\"$Instance\"}[$__rate_interval])",
     "legendFormat": "Bytes Allocated"
    }
   ]
  },
  {
   "title": "WAL bytes & FPI / s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(pg_stat_wal_wal_bytes{instance=\"$Instance\",server=\"$Server\"}[$__rate_interval])",
     "legendFormat": "WAL bytes"
    },
    {
     "expr": "rate(pg_stat_wal_wal_fpi{instance=\"$Instance\",server=\"$Server\"}[$__rate_interval])",
     "legendFormat": "WAL FPI"
    }
   ]
  },
  {
   "title": "I/O Read/Write time",
   "type": "timeseries",
   "description": "* blk_read_time: Time spent reading data file blocks by backends in this database, in milliseconds\n* blk_write_time: Time spent writing data file blocks by backends in this database, in milliseconds\n\ntrack_io_timings needs to be activated",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum ((rate(pg_stat_database_blk_read_time{instance=\"$Instance\"}[$__rate_interval])))",
     "legendFormat": "blk_read_time"
    },
    {
     "expr": "sum ((rate(pg_stat_database_blk_write_time{instance=\"$Instance\"}[$__rate_interval])))",
     "legendFormat": "blk_read_time"
    }
   ]
  },
  {
   "title": "Temporary files by database",
   "type": "timeseries",
   "description": "Should be 0. If temporary files are created, it can indicate insufficient work_mem. With log_temp_files the creation of temporary files are logged to the PostgreSQL Logfiles.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (datname) ((rate(pg_stat_database_temp_files{instance=\"$Instance\"}[$__rate_interval])))",
     "legendFormat": "{{datname}}"
    }
   ]
  }
 ]
}