{
 "title": "System Resources",
 "tags": [ "postgresql" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Instance",
    "label": "Exporter",
    "query": {
     "query": "label_values({job=\"postgres\"},instance)"
    }
   },
   {
    "name": "Database",
    "query": {
     "query": "label_values({job=\"postgres\"},datname)"
    }
   },
   {
    "name": "Server",
    "query": {
     "query": "label_values({job=\"postgres\"},server)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Queries CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pg_stat_kcache_plan_user_time{datname=\"$Database\",instance=\"$Instance\",server=\"$Server\"}[$__rate_interval])",
     "legendFormat": "Plan User Time"
    },
    {
     "expr": "rate(pg_stat_kcache_plan_system_time{datname=\"$Database\",instance=\"$Instance\",server=\"$Server\"}[$__rate_interval])",
     "legendFormat": "Plan System Time"
    },
    {
     "expr": "rate(pg_stat_kcache_exec_user_time{datname=\"$Database\",instance=\"$Instance\",server=\"$Server\"}[$__rate_interval])",
     "legendFormat": "Execution User Time"
    },
    {
     "expr": "rate(pg_stat_kcache_exec_system_time{datname=\"$Database\",instance=\"$Instance\",server=\"$Server\"}[$__rate_interval])",
     "legendFormat": "Execution System Time"
    }
   ]
  },
  {
   "title": "Disk Reads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(pg_stat_kcache_plan_reads{datname=\"$Database\",instance=\"$Instance\",server=\"$Server\"}[$__rate_interval])",
     "legendFormat": "Plan Reads"
    },
    {
     "expr": "rate(pg_stat_kcache_exec_reads{datname=\"$Database\",instance=\"$Instance\",server=\"$Server\"}[$__rate_interval])",
     "legendFormat": "Execution Reads"
    }
   ]
  },
  {
   "title": "Disk Writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(pg_stat_kcache_plan_writes{datname=\"$Database\",instance=\"$Instance\",server=\"$Server\"}[$__rate_interval])",
     "legendFormat": "Plan Writes"
    },
    {
     "expr": "rate(pg_stat_kcache_exec_writes{datname=\"$Database\",instance=\"$Instance\",server=\"$Server\"}[$__rate_interval])",
     "legendFormat": "Execution Writes"
    }
   ]
  }
 ]
}