{
 "title": "Table Details",
 "description": "postgres exporter Dashboard for display important postgreSQL metric",
 "tags": [ "postgresql" ],
 "time": { "from": "2024-04-24T18:22:37.173Z", "to": "2024-04-24T18:37:10.809Z" },
 "templating": {
  "list": [
   {
    "name": "Instance",
    "label": "Exporter",
    "query": {
     "query": "label_values({job=\"postgres\"},instance)"
    }
   },
   {
    "name": "Server",
    "query": {
     "query": "label_values({job=\"postgres\"},server)"
    }
   },
   { "name": "Database", "query": { "query": "label_values(datname)" } },
   {
    "name": "Table",
    "query": {
     "query": "label_values({job=\"postgres\"},relname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Inserts, Updates, Deletes Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_n_tup_ins{datname=\"$Database\",server=\"$Server\",instance=\"$Instance\",relname=\"$Table\"}[$__rate_interval])",
     "legendFormat": "Inserts"
    },
    {
     "expr": "rate(pg_stat_user_tables_n_tup_upd{datname=\"$Database\",server=\"$Server\",instance=\"$Instance\",relname=\"$Table\"}[$__rate_interval])",
     "legendFormat": "Updates"
    },
    {
     "expr": "rate(pg_stat_user_tables_n_tup_del{datname=\"$Database\",server=\"$Server\",instance=\"$Instance\",relname=\"$Table\"}[$__rate_interval])",
     "legendFormat": "Deletes"
    },
    {
     "expr": "rate(pg_stat_user_tables_n_tup_hot_upd{datname=\"$Database\",server=\"$Server\",instance=\"$Instance\",relname=\"$Table\"}[$__rate_interval])",
     "legendFormat": "HOT Updates"
    }
   ]
  },
  {
   "title": "Heap and Index Hits",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "8192*rate(pg_statio_user_tables_heap_blks_hit{datname=\"$Database\",server=\"$Server\",instance=\"$Instance\",relname=\"$Table\"}[$__rate_interval])",
     "legendFormat": "Heap Hits"
    },
    {
     "expr": "8192*rate(pg_statio_user_tables_idx_blks_hit{datname=\"$Database\",server=\"$Server\",instance=\"$Instance\",relname=\"$Table\"}[$__rate_interval])",
     "legendFormat": "Index Hits"
    }
   ]
  },
  {
   "title": "Sequential vs Index Scans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_seq_scan{datname=\"$Database\",server=\"$Server\",instance=\"$Instance\",relname=\"$Table\"}[$__rate_interval])",
     "legendFormat": "Sequential"
    },
    {
     "expr": "rate(pg_stat_user_tables_idx_scan{datname=\"$Database\",server=\"$Server\",instance=\"$Instance\",relname=\"$Table\"}[$__rate_interval])",
     "legendFormat": "Index"
    }
   ]
  },
  {
   "title": "Heap and Index Reads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "8192*rate(pg_statio_user_tables_heap_blks_read{datname=\"$Database\",server=\"$Server\",instance=\"$Instance\",relname=\"$Table\"}[$__rate_interval])",
     "legendFormat": "Heap Reads"
    },
    {
     "expr": "8192*rate(pg_statio_user_tables_idx_blks_read{datname=\"$Database\",server=\"$Server\",instance=\"$Instance\",relname=\"$Table\"}[$__rate_interval])",
     "legendFormat": "Index Reads"
    }
   ]
  },
  {
   "title": "Percentage of Dead Tuples",
   "type": "timeseries",
   "description": "Shows top $Top tables with highest percentage of dead tuples over total number of tuples in the table.\nNote: this considers only number of tuples, not their size. So if it shows high numbers for a very small table, it may mean nothing.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*(pg_stat_user_tables_n_dead_tup{datname=\"portnov\",server=\"$Server\",instance=\"$Instance\",relname=\"$Table\"} / (pg_stat_user_tables_n_live_tup{datname=\"portnov\",server=\"$Server\",instance=\"$Instance\",relname=\"$Table\"} != 0 + pg_stat_user_tables_n_dead_tup{datname=\"portnov\",server=\"$Server\",instance=\"$Instance\",relname=\"$Table\"} > 50))",
     "legendFormat": "{{schemaname}}.{{relname}}"
    }
   ]
  },
  {
   "title": "Dead Tuples Growth",
   "type": "timeseries",
   "description": "Shows growth of number of dead tuples per table.\nNote 1: this is in fact a derivative of number of dead tuples. So, if this graph shows constant value, this means that number of dead tuples grows linear. If this graph shows growth, it means number of dead tuples grows quadratically.\nNote 2: Negative values indicate that vacuum does it's job.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "delta(pg_stat_user_tables_n_dead_tup{datname=\"$Database\",server=\"$Server\",instance=\"$Instance\",relname=\"$Table\"}[$__rate_interval])",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Dead vs Live Tuples",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_live_tup{datname=\"portnov\",server=\"$Server\",instance=\"$Instance\",relname=\"$Table\"}",
     "legendFormat": "Live Tuples"
    },
    {
     "expr": "pg_stat_user_tables_n_dead_tup{datname=\"portnov\",server=\"$Server\",instance=\"$Instance\",relname=\"$Table\"}",
     "legendFormat": "Dead Tuples"
    }
   ]
  },
  {
   "title": "Autovacuum Activity",
   "type": "timeseries",
   "description": "Displays number of autovacuum invocations per table.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_autovacuum_count{datname=\"$Database\",server=\"$Server\",instance=\"$Instance\",relname=\"$Table\"}[$__rate_interval])",
     "legendFormat": "Autovacuum Events"
    }
   ]
  }
 ]
}