{
 "title": "Top Tables",
 "tags": [ "postgresql" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Database", "query": { "query": "label_values(datname)" } }
  ]
 },
 "panels": [
  { "title": "Logical Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sequentially Scanned Tables",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_seq_scan{datname=\"$Database\"}[$__rate_interval])",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Inserts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_n_tup_ins{datname=\"$Database\"}[$__rate_interval]) > 0",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Index Scanned Tables",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_idx_scan{datname=\"$Database\"}[$__rate_interval]) > 1",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Updates",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_n_tup_upd{datname=\"$Database\"}[$__rate_interval]) > 0",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Deletes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_n_tup_del{datname=\"$Database\"}[$__rate_interval]) > 0",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  { "title": "Shared Buffers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Heap Blocks Hit",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "rate(pg_statio_user_tables_heap_blks_hit{datname=\"$Database\"}[$__rate_interval]) > 1",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Index Blocks Hit",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "rate(pg_statio_user_tables_idx_blks_hit{datname=\"$Database\"}[$__rate_interval]) > 1",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Heap Blocks Read",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "rate(pg_statio_user_tables_heap_blks_read{datname=\"$Database\"}[$__rate_interval]) > 0",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Index Blocks Read",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "rate(pg_statio_user_tables_idx_blks_read{datname=\"$Database\"}[$__rate_interval]) > 1",
     "legendFormat": "{{relname}}"
    }
   ]
  }
 ]
}